---
title: "Gov 50 Final Project"
author: "Ted Sunshine"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to how various climates/temperatures around the world can affect individual nations economic and industrial productivity. Test.

## Data Backed Proposal

Does climate have an impact on a region’s productivity? For this project, I’ll analyze the relationship between these two factors by examining how a region’s temperature and climate cycle affect a nation’s GDP and GDP per capita. I hypothesize that nations with warmer climates are more likely to see lower levels of GDP per capita and overall productivity. My sample is a study by the NOAA (National Oceanic and Atmospheric Administration) and assesses the productivity of American counties by temperature, pressure, and precipitation. The study aims to narrow down which regions of the country are most economically affected by temperature and weather differences. The coded variables will be based on temperature, precipitation, and pressure, and they will act as the dependent variables. The dependent variable will be GDP per capita, coded by its pure numeric value in the data. A result of high temperatures and either extremely high or low precipitation being correlated with low GDP per capita would indicate that my hypothesis is correct. 

